---
- name: Remove all existing dockers in elk stack vm's
  hosts: elk
  become: true
  tasks:
    - name: Docker Contatiner Removal
      docker_container:
        state: absent
        name: elk
        image: sebp/elk:761
    - name: Docker Image removal
      docker_image:
        name: sebp/elk:761
        repository: sebp/elk:761
        state: absent
        # working
