---
- name: Install MetricBeat Ansible PlayBook
  hosts: webservers
  become: true
  tasks:
    - name: Curl metricbeat.deb
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

    - name: Unpackage metricbeat
      command: sudo dpkg -i metricbeat-7.6.1-amd64.deb

    - name: Copy Config
      copy:
        src: /root/CyberXSecurity-Project-1/MetricBeat/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml
    
    - name: MetricBeat enabled docker
      command: metricbeat modules enable docker

    - name: MetricBeat setup
      command: metricbeat setup

    - name: MetricBeat setup
      command: metricbeat -e

    - name: service metricbeat start
      command: service metricbeat start

    - name: Enable MetricBeat service
      systemd:
        name: metricbeat
        enabled: yes