---
- name: Install MetricBeat Ansible PlayBook
  hosts: webservers
  become: true
  tasks:
    - name: Curl metricbeat.deb
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

    - name: Unpackage metricbeat
      debugger: on_failed
      command: sudo dpkg -i metricbeat-7.6.1-amd64.deb

    - name: Copy Config
      copy:
        src: /root/CyberXSecurity-Project-1/MetricBeat/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml

    - name: remove docker.yml
      command: sudo rm /etc/metricbeat/modules.d/docker.yml
      
    - name: Copy Config
      copy:
        src: /root/CyberXSecurity-Project-1/MetricBeat/metricbeat-docker-config.yml
        dest: /etc/metricbeat/modules.d/docker.yml
    
    - name: MetricBeat enabled docker
      command: sudo metricbeat modules enable docker

    - name: MetricBeat setup
      debugger: on_failed
      command: sudo metricbeat setup

    - name: service metricbeat start
      command: sudo service metricbeat restart

    - name: Enable MetricBeat service
      systemd:
        name: metricbeat
        enabled: yes