---
- name: Install FileBeat Ansible PlayBook
  hosts: webservers
  become: true
  tasks:
    - name: Curl filebeat.deb
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb

    - name: Unpackage filebeat
      command: sudo dpkg -i filebeat-7.6.1-amd64.deb

    - name: Copy Config
      copy:
        # remote_src: yes
        # src: https://github.com/Logicye/CyberXSecurity-Project-1/blob/38a6dc28c17973027d0a34a16084282b0963f0f6/FileBeat/filebeat-config.yml
        src: /root/CyberXSecurity-Project-1/FileBeat/filebeat-config.yml
        dest: /etc/filebeat/filebeat.yml
    
    - name: FileBeat enabled
      command: sudo filebeat modules enable system

    - name: FileBeat setup
      command: sudo filebeat setup

    - name: service filebeat start
      command: sudo service filebeat start

    - name: Enable FileBeat service
      systemd:
        name: filebeat
        enabled: yes